### ISSUE TITLE
What's wrong with the code below??

### ISSUE THREAD

**Issue by mustafaertekin** [mustafaertekin/js-week2-assignment#1]
function upDate(previewPic){
  var imageSRC = previewPic.src;
  document.getElementById('image').style.backgroundImage = 'url('imageSRC');
}

**Comment by mustafaertekin** [comment]
'url('   +  imageSRC  +  ')'

**Comment by domch** [comment]
You have to concatenate the string in the right way.
The point is, js strings are concatenated by plus sign in the javascript and you have to be beware of using the character escaping, if you wanna use the single quotes repeatedly in your string.
